name: Upload Python Package to PyPI

on:
  release:
    types: [published]


permissions:
  
  contents: read
  
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: pypi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1